### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by hana-0612** [hana-0612/protospace-36029#1]
■URL
https://protospace-36029.herokuapp.com/

**Comment by snkw-works** [comment]
@hana-0612 さん、お待たせいたしました。ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by hana-0612** [comment]
ご確認いただきありがとうございます。引き続きよろしくお願いいたします✨
